// Generated by scripts/generate_extended_tests.py; edit the scenario table there.
// clang-format off
#include "extended/numeric_cases.hpp"

CH_TEST(functional_numeric_float_quadratic_roots_known_scenario0) {
    extended_numeric::quadratic_roots_known<float, 0>();
}

CH_TEST(functional_numeric_float_quadratic_roots_known_scenario1) {
    extended_numeric::quadratic_roots_known<float, 1>();
}

CH_TEST(functional_numeric_float_quadratic_roots_known_scenario2) {
    extended_numeric::quadratic_roots_known<float, 2>();
}

CH_TEST(functional_numeric_float_quadratic_roots_known_scenario3) {
    extended_numeric::quadratic_roots_known<float, 3>();
}

CH_TEST(functional_numeric_float_horner_reference_scenario0) {
    extended_numeric::horner_reference<float, 0>();
}

CH_TEST(functional_numeric_float_horner_reference_scenario1) {
    extended_numeric::horner_reference<float, 1>();
}

CH_TEST(functional_numeric_float_horner_reference_scenario2) {
    extended_numeric::horner_reference<float, 2>();
}

CH_TEST(functional_numeric_float_horner_reference_scenario3) {
    extended_numeric::horner_reference<float, 3>();
}

CH_TEST(functional_numeric_float_bisect_irrational_scenario0) {
    extended_numeric::bisect_irrational<float, 0>();
}

CH_TEST(functional_numeric_float_bisect_irrational_scenario1) {
    extended_numeric::bisect_irrational<float, 1>();
}

CH_TEST(functional_numeric_float_bisect_irrational_scenario2) {
    extended_numeric::bisect_irrational<float, 2>();
}

CH_TEST(functional_numeric_float_bisect_irrational_scenario3) {
    extended_numeric::bisect_irrational<float, 3>();
}

CH_TEST(functional_numeric_float_integrate_polynomial_scenario0) {
    extended_numeric::integrate_polynomial<float, 0>();
}

CH_TEST(functional_numeric_float_integrate_polynomial_scenario1) {
    extended_numeric::integrate_polynomial<float, 1>();
}

CH_TEST(functional_numeric_float_integrate_polynomial_scenario2) {
    extended_numeric::integrate_polynomial<float, 2>();
}

CH_TEST(functional_numeric_float_integrate_polynomial_scenario3) {
    extended_numeric::integrate_polynomial<float, 3>();
}

CH_TEST(functional_numeric_float_compensated_cancellation_scenario0) {
    extended_numeric::compensated_cancellation<float, 0>();
}

CH_TEST(functional_numeric_float_compensated_cancellation_scenario1) {
    extended_numeric::compensated_cancellation<float, 1>();
}

CH_TEST(functional_numeric_float_compensated_cancellation_scenario2) {
    extended_numeric::compensated_cancellation<float, 2>();
}

CH_TEST(functional_numeric_float_compensated_cancellation_scenario3) {
    extended_numeric::compensated_cancellation<float, 3>();
}

CH_TEST(functional_numeric_float_bounded_root_work_scenario0) {
    extended_numeric::bounded_root_work<float, 0>();
}

CH_TEST(functional_numeric_float_bounded_root_work_scenario1) {
    extended_numeric::bounded_root_work<float, 1>();
}

CH_TEST(functional_numeric_float_bounded_root_work_scenario2) {
    extended_numeric::bounded_root_work<float, 2>();
}

CH_TEST(functional_numeric_float_bounded_root_work_scenario3) {
    extended_numeric::bounded_root_work<float, 3>();
}

CH_TEST(functional_numeric_double_quadratic_roots_known_scenario0) {
    extended_numeric::quadratic_roots_known<double, 0>();
}

CH_TEST(functional_numeric_double_quadratic_roots_known_scenario1) {
    extended_numeric::quadratic_roots_known<double, 1>();
}

CH_TEST(functional_numeric_double_quadratic_roots_known_scenario2) {
    extended_numeric::quadratic_roots_known<double, 2>();
}

CH_TEST(functional_numeric_double_quadratic_roots_known_scenario3) {
    extended_numeric::quadratic_roots_known<double, 3>();
}

CH_TEST(functional_numeric_double_horner_reference_scenario0) {
    extended_numeric::horner_reference<double, 0>();
}

CH_TEST(functional_numeric_double_horner_reference_scenario1) {
    extended_numeric::horner_reference<double, 1>();
}

CH_TEST(functional_numeric_double_horner_reference_scenario2) {
    extended_numeric::horner_reference<double, 2>();
}

CH_TEST(functional_numeric_double_horner_reference_scenario3) {
    extended_numeric::horner_reference<double, 3>();
}

CH_TEST(functional_numeric_double_bisect_irrational_scenario0) {
    extended_numeric::bisect_irrational<double, 0>();
}

CH_TEST(functional_numeric_double_bisect_irrational_scenario1) {
    extended_numeric::bisect_irrational<double, 1>();
}

CH_TEST(functional_numeric_double_bisect_irrational_scenario2) {
    extended_numeric::bisect_irrational<double, 2>();
}

CH_TEST(functional_numeric_double_bisect_irrational_scenario3) {
    extended_numeric::bisect_irrational<double, 3>();
}

CH_TEST(functional_numeric_double_integrate_polynomial_scenario0) {
    extended_numeric::integrate_polynomial<double, 0>();
}

CH_TEST(functional_numeric_double_integrate_polynomial_scenario1) {
    extended_numeric::integrate_polynomial<double, 1>();
}

CH_TEST(functional_numeric_double_integrate_polynomial_scenario2) {
    extended_numeric::integrate_polynomial<double, 2>();
}

CH_TEST(functional_numeric_double_integrate_polynomial_scenario3) {
    extended_numeric::integrate_polynomial<double, 3>();
}

CH_TEST(functional_numeric_double_compensated_cancellation_scenario0) {
    extended_numeric::compensated_cancellation<double, 0>();
}

CH_TEST(functional_numeric_double_compensated_cancellation_scenario1) {
    extended_numeric::compensated_cancellation<double, 1>();
}

CH_TEST(functional_numeric_double_compensated_cancellation_scenario2) {
    extended_numeric::compensated_cancellation<double, 2>();
}

CH_TEST(functional_numeric_double_compensated_cancellation_scenario3) {
    extended_numeric::compensated_cancellation<double, 3>();
}

CH_TEST(functional_numeric_double_bounded_root_work_scenario0) {
    extended_numeric::bounded_root_work<double, 0>();
}

CH_TEST(functional_numeric_double_bounded_root_work_scenario1) {
    extended_numeric::bounded_root_work<double, 1>();
}

CH_TEST(functional_numeric_double_bounded_root_work_scenario2) {
    extended_numeric::bounded_root_work<double, 2>();
}

CH_TEST(functional_numeric_double_bounded_root_work_scenario3) {
    extended_numeric::bounded_root_work<double, 3>();
}
