// Generated by scripts/generate_extended_tests.py; edit the scenario table there.
// clang-format off
#include "extended/stress_cases.hpp"

CH_TEST(stress_float_normalization_tier0) {
    extended_stress::run<float, 0, 0>();
}

CH_TEST(stress_float_normalization_tier1) {
    extended_stress::run<float, 0, 1>();
}

CH_TEST(stress_float_normalization_tier2) {
    extended_stress::run<float, 0, 2>();
}

CH_TEST(stress_float_rotation_chain_tier0) {
    extended_stress::run<float, 1, 0>();
}

CH_TEST(stress_float_rotation_chain_tier1) {
    extended_stress::run<float, 1, 1>();
}

CH_TEST(stress_float_rotation_chain_tier2) {
    extended_stress::run<float, 1, 2>();
}

CH_TEST(stress_float_affine_chain_tier0) {
    extended_stress::run<float, 2, 0>();
}

CH_TEST(stress_float_affine_chain_tier1) {
    extended_stress::run<float, 2, 1>();
}

CH_TEST(stress_float_affine_chain_tier2) {
    extended_stress::run<float, 2, 2>();
}

CH_TEST(stress_float_lu_reuse_tier0) {
    extended_stress::run<float, 3, 0>();
}

CH_TEST(stress_float_lu_reuse_tier1) {
    extended_stress::run<float, 3, 1>();
}

CH_TEST(stress_float_lu_reuse_tier2) {
    extended_stress::run<float, 3, 2>();
}

CH_TEST(stress_float_ray_grid_tier0) {
    extended_stress::run<float, 4, 0>();
}

CH_TEST(stress_float_ray_grid_tier1) {
    extended_stress::run<float, 4, 1>();
}

CH_TEST(stress_float_ray_grid_tier2) {
    extended_stress::run<float, 4, 2>();
}

CH_TEST(stress_float_spline_sampling_tier0) {
    extended_stress::run<float, 5, 0>();
}

CH_TEST(stress_float_spline_sampling_tier1) {
    extended_stress::run<float, 5, 1>();
}

CH_TEST(stress_float_spline_sampling_tier2) {
    extended_stress::run<float, 5, 2>();
}

CH_TEST(stress_float_batch_pipeline_tier0) {
    extended_stress::run<float, 6, 0>();
}

CH_TEST(stress_float_batch_pipeline_tier1) {
    extended_stress::run<float, 6, 1>();
}

CH_TEST(stress_float_batch_pipeline_tier2) {
    extended_stress::run<float, 6, 2>();
}

CH_TEST(stress_float_conditioned_inverse_tier0) {
    extended_stress::run<float, 7, 0>();
}

CH_TEST(stress_float_conditioned_inverse_tier1) {
    extended_stress::run<float, 7, 1>();
}

CH_TEST(stress_float_conditioned_inverse_tier2) {
    extended_stress::run<float, 7, 2>();
}

CH_TEST(stress_float_integration_tier0) {
    extended_stress::run<float, 8, 0>();
}

CH_TEST(stress_float_integration_tier1) {
    extended_stress::run<float, 8, 1>();
}

CH_TEST(stress_float_integration_tier2) {
    extended_stress::run<float, 8, 2>();
}

CH_TEST(stress_float_concurrent_readers_tier0) {
    extended_stress::run<float, 9, 0>();
}

CH_TEST(stress_float_concurrent_readers_tier1) {
    extended_stress::run<float, 9, 1>();
}

CH_TEST(stress_float_concurrent_readers_tier2) {
    extended_stress::run<float, 9, 2>();
}

CH_TEST(stress_double_normalization_tier0) {
    extended_stress::run<double, 0, 0>();
}

CH_TEST(stress_double_normalization_tier1) {
    extended_stress::run<double, 0, 1>();
}

CH_TEST(stress_double_normalization_tier2) {
    extended_stress::run<double, 0, 2>();
}

CH_TEST(stress_double_rotation_chain_tier0) {
    extended_stress::run<double, 1, 0>();
}

CH_TEST(stress_double_rotation_chain_tier1) {
    extended_stress::run<double, 1, 1>();
}

CH_TEST(stress_double_rotation_chain_tier2) {
    extended_stress::run<double, 1, 2>();
}

CH_TEST(stress_double_affine_chain_tier0) {
    extended_stress::run<double, 2, 0>();
}

CH_TEST(stress_double_affine_chain_tier1) {
    extended_stress::run<double, 2, 1>();
}

CH_TEST(stress_double_affine_chain_tier2) {
    extended_stress::run<double, 2, 2>();
}

CH_TEST(stress_double_lu_reuse_tier0) {
    extended_stress::run<double, 3, 0>();
}

CH_TEST(stress_double_lu_reuse_tier1) {
    extended_stress::run<double, 3, 1>();
}

CH_TEST(stress_double_lu_reuse_tier2) {
    extended_stress::run<double, 3, 2>();
}

CH_TEST(stress_double_ray_grid_tier0) {
    extended_stress::run<double, 4, 0>();
}

CH_TEST(stress_double_ray_grid_tier1) {
    extended_stress::run<double, 4, 1>();
}

CH_TEST(stress_double_ray_grid_tier2) {
    extended_stress::run<double, 4, 2>();
}

CH_TEST(stress_double_spline_sampling_tier0) {
    extended_stress::run<double, 5, 0>();
}

CH_TEST(stress_double_spline_sampling_tier1) {
    extended_stress::run<double, 5, 1>();
}

CH_TEST(stress_double_spline_sampling_tier2) {
    extended_stress::run<double, 5, 2>();
}

CH_TEST(stress_double_batch_pipeline_tier0) {
    extended_stress::run<double, 6, 0>();
}

CH_TEST(stress_double_batch_pipeline_tier1) {
    extended_stress::run<double, 6, 1>();
}

CH_TEST(stress_double_batch_pipeline_tier2) {
    extended_stress::run<double, 6, 2>();
}

CH_TEST(stress_double_conditioned_inverse_tier0) {
    extended_stress::run<double, 7, 0>();
}

CH_TEST(stress_double_conditioned_inverse_tier1) {
    extended_stress::run<double, 7, 1>();
}

CH_TEST(stress_double_conditioned_inverse_tier2) {
    extended_stress::run<double, 7, 2>();
}

CH_TEST(stress_double_integration_tier0) {
    extended_stress::run<double, 8, 0>();
}

CH_TEST(stress_double_integration_tier1) {
    extended_stress::run<double, 8, 1>();
}

CH_TEST(stress_double_integration_tier2) {
    extended_stress::run<double, 8, 2>();
}

CH_TEST(stress_double_concurrent_readers_tier0) {
    extended_stress::run<double, 9, 0>();
}

CH_TEST(stress_double_concurrent_readers_tier1) {
    extended_stress::run<double, 9, 1>();
}

CH_TEST(stress_double_concurrent_readers_tier2) {
    extended_stress::run<double, 9, 2>();
}
