// Generated by scripts/generate_extended_tests.py; edit the scenario table there.
// clang-format off
#include "extended/vector_cases.hpp"

CH_TEST(functional_vector_float_n1_addition) {
    extended_vector::addition<float, 1>();
}

CH_TEST(functional_vector_float_n1_subtraction) {
    extended_vector::subtraction<float, 1>();
}

CH_TEST(functional_vector_float_n1_scaling) {
    extended_vector::scaling<float, 1>();
}

CH_TEST(functional_vector_float_n1_component_product) {
    extended_vector::component_product<float, 1>();
}

CH_TEST(functional_vector_float_n1_dot_reference) {
    extended_vector::dot_reference<float, 1>();
}

CH_TEST(functional_vector_float_n1_normalize_reference) {
    extended_vector::normalize_reference<float, 1>();
}

CH_TEST(functional_vector_float_n1_projection_residual) {
    extended_vector::projection_residual<float, 1>();
}

CH_TEST(functional_vector_float_n1_angle_invariants) {
    extended_vector::angle_invariants<float, 1>();
}

CH_TEST(functional_vector_float_n1_length_extremes) {
    extended_vector::length_extremes<float, 1>();
}

CH_TEST(functional_vector_float_n1_packed_storage) {
    extended_vector::packed_storage<float, 1>();
}

CH_TEST(functional_vector_float_n2_addition) {
    extended_vector::addition<float, 2>();
}

CH_TEST(functional_vector_float_n2_subtraction) {
    extended_vector::subtraction<float, 2>();
}

CH_TEST(functional_vector_float_n2_scaling) {
    extended_vector::scaling<float, 2>();
}

CH_TEST(functional_vector_float_n2_component_product) {
    extended_vector::component_product<float, 2>();
}

CH_TEST(functional_vector_float_n2_dot_reference) {
    extended_vector::dot_reference<float, 2>();
}

CH_TEST(functional_vector_float_n2_normalize_reference) {
    extended_vector::normalize_reference<float, 2>();
}

CH_TEST(functional_vector_float_n2_projection_residual) {
    extended_vector::projection_residual<float, 2>();
}

CH_TEST(functional_vector_float_n2_angle_invariants) {
    extended_vector::angle_invariants<float, 2>();
}

CH_TEST(functional_vector_float_n2_length_extremes) {
    extended_vector::length_extremes<float, 2>();
}

CH_TEST(functional_vector_float_n2_packed_storage) {
    extended_vector::packed_storage<float, 2>();
}

CH_TEST(functional_vector_float_n3_addition) {
    extended_vector::addition<float, 3>();
}

CH_TEST(functional_vector_float_n3_subtraction) {
    extended_vector::subtraction<float, 3>();
}

CH_TEST(functional_vector_float_n3_scaling) {
    extended_vector::scaling<float, 3>();
}

CH_TEST(functional_vector_float_n3_component_product) {
    extended_vector::component_product<float, 3>();
}

CH_TEST(functional_vector_float_n3_dot_reference) {
    extended_vector::dot_reference<float, 3>();
}

CH_TEST(functional_vector_float_n3_normalize_reference) {
    extended_vector::normalize_reference<float, 3>();
}

CH_TEST(functional_vector_float_n3_projection_residual) {
    extended_vector::projection_residual<float, 3>();
}

CH_TEST(functional_vector_float_n3_angle_invariants) {
    extended_vector::angle_invariants<float, 3>();
}

CH_TEST(functional_vector_float_n3_length_extremes) {
    extended_vector::length_extremes<float, 3>();
}

CH_TEST(functional_vector_float_n3_packed_storage) {
    extended_vector::packed_storage<float, 3>();
}

CH_TEST(functional_vector_float_n4_addition) {
    extended_vector::addition<float, 4>();
}

CH_TEST(functional_vector_float_n4_subtraction) {
    extended_vector::subtraction<float, 4>();
}

CH_TEST(functional_vector_float_n4_scaling) {
    extended_vector::scaling<float, 4>();
}

CH_TEST(functional_vector_float_n4_component_product) {
    extended_vector::component_product<float, 4>();
}

CH_TEST(functional_vector_float_n4_dot_reference) {
    extended_vector::dot_reference<float, 4>();
}

CH_TEST(functional_vector_float_n4_normalize_reference) {
    extended_vector::normalize_reference<float, 4>();
}

CH_TEST(functional_vector_float_n4_projection_residual) {
    extended_vector::projection_residual<float, 4>();
}

CH_TEST(functional_vector_float_n4_angle_invariants) {
    extended_vector::angle_invariants<float, 4>();
}

CH_TEST(functional_vector_float_n4_length_extremes) {
    extended_vector::length_extremes<float, 4>();
}

CH_TEST(functional_vector_float_n4_packed_storage) {
    extended_vector::packed_storage<float, 4>();
}

CH_TEST(functional_vector_float_n8_addition) {
    extended_vector::addition<float, 8>();
}

CH_TEST(functional_vector_float_n8_subtraction) {
    extended_vector::subtraction<float, 8>();
}

CH_TEST(functional_vector_float_n8_scaling) {
    extended_vector::scaling<float, 8>();
}

CH_TEST(functional_vector_float_n8_component_product) {
    extended_vector::component_product<float, 8>();
}

CH_TEST(functional_vector_float_n8_dot_reference) {
    extended_vector::dot_reference<float, 8>();
}

CH_TEST(functional_vector_float_n8_normalize_reference) {
    extended_vector::normalize_reference<float, 8>();
}

CH_TEST(functional_vector_float_n8_projection_residual) {
    extended_vector::projection_residual<float, 8>();
}

CH_TEST(functional_vector_float_n8_angle_invariants) {
    extended_vector::angle_invariants<float, 8>();
}

CH_TEST(functional_vector_float_n8_length_extremes) {
    extended_vector::length_extremes<float, 8>();
}

CH_TEST(functional_vector_float_n8_packed_storage) {
    extended_vector::packed_storage<float, 8>();
}

CH_TEST(functional_vector_float_n16_addition) {
    extended_vector::addition<float, 16>();
}

CH_TEST(functional_vector_float_n16_subtraction) {
    extended_vector::subtraction<float, 16>();
}

CH_TEST(functional_vector_float_n16_scaling) {
    extended_vector::scaling<float, 16>();
}

CH_TEST(functional_vector_float_n16_component_product) {
    extended_vector::component_product<float, 16>();
}

CH_TEST(functional_vector_float_n16_dot_reference) {
    extended_vector::dot_reference<float, 16>();
}

CH_TEST(functional_vector_float_n16_normalize_reference) {
    extended_vector::normalize_reference<float, 16>();
}

CH_TEST(functional_vector_float_n16_projection_residual) {
    extended_vector::projection_residual<float, 16>();
}

CH_TEST(functional_vector_float_n16_angle_invariants) {
    extended_vector::angle_invariants<float, 16>();
}

CH_TEST(functional_vector_float_n16_length_extremes) {
    extended_vector::length_extremes<float, 16>();
}

CH_TEST(functional_vector_float_n16_packed_storage) {
    extended_vector::packed_storage<float, 16>();
}

CH_TEST(functional_vector_double_n1_addition) {
    extended_vector::addition<double, 1>();
}

CH_TEST(functional_vector_double_n1_subtraction) {
    extended_vector::subtraction<double, 1>();
}

CH_TEST(functional_vector_double_n1_scaling) {
    extended_vector::scaling<double, 1>();
}

CH_TEST(functional_vector_double_n1_component_product) {
    extended_vector::component_product<double, 1>();
}

CH_TEST(functional_vector_double_n1_dot_reference) {
    extended_vector::dot_reference<double, 1>();
}

CH_TEST(functional_vector_double_n1_normalize_reference) {
    extended_vector::normalize_reference<double, 1>();
}

CH_TEST(functional_vector_double_n1_projection_residual) {
    extended_vector::projection_residual<double, 1>();
}

CH_TEST(functional_vector_double_n1_angle_invariants) {
    extended_vector::angle_invariants<double, 1>();
}

CH_TEST(functional_vector_double_n1_length_extremes) {
    extended_vector::length_extremes<double, 1>();
}

CH_TEST(functional_vector_double_n1_packed_storage) {
    extended_vector::packed_storage<double, 1>();
}

CH_TEST(functional_vector_double_n2_addition) {
    extended_vector::addition<double, 2>();
}

CH_TEST(functional_vector_double_n2_subtraction) {
    extended_vector::subtraction<double, 2>();
}

CH_TEST(functional_vector_double_n2_scaling) {
    extended_vector::scaling<double, 2>();
}

CH_TEST(functional_vector_double_n2_component_product) {
    extended_vector::component_product<double, 2>();
}

CH_TEST(functional_vector_double_n2_dot_reference) {
    extended_vector::dot_reference<double, 2>();
}

CH_TEST(functional_vector_double_n2_normalize_reference) {
    extended_vector::normalize_reference<double, 2>();
}

CH_TEST(functional_vector_double_n2_projection_residual) {
    extended_vector::projection_residual<double, 2>();
}

CH_TEST(functional_vector_double_n2_angle_invariants) {
    extended_vector::angle_invariants<double, 2>();
}

CH_TEST(functional_vector_double_n2_length_extremes) {
    extended_vector::length_extremes<double, 2>();
}

CH_TEST(functional_vector_double_n2_packed_storage) {
    extended_vector::packed_storage<double, 2>();
}

CH_TEST(functional_vector_double_n3_addition) {
    extended_vector::addition<double, 3>();
}

CH_TEST(functional_vector_double_n3_subtraction) {
    extended_vector::subtraction<double, 3>();
}

CH_TEST(functional_vector_double_n3_scaling) {
    extended_vector::scaling<double, 3>();
}

CH_TEST(functional_vector_double_n3_component_product) {
    extended_vector::component_product<double, 3>();
}

CH_TEST(functional_vector_double_n3_dot_reference) {
    extended_vector::dot_reference<double, 3>();
}

CH_TEST(functional_vector_double_n3_normalize_reference) {
    extended_vector::normalize_reference<double, 3>();
}

CH_TEST(functional_vector_double_n3_projection_residual) {
    extended_vector::projection_residual<double, 3>();
}

CH_TEST(functional_vector_double_n3_angle_invariants) {
    extended_vector::angle_invariants<double, 3>();
}

CH_TEST(functional_vector_double_n3_length_extremes) {
    extended_vector::length_extremes<double, 3>();
}

CH_TEST(functional_vector_double_n3_packed_storage) {
    extended_vector::packed_storage<double, 3>();
}

CH_TEST(functional_vector_double_n4_addition) {
    extended_vector::addition<double, 4>();
}

CH_TEST(functional_vector_double_n4_subtraction) {
    extended_vector::subtraction<double, 4>();
}

CH_TEST(functional_vector_double_n4_scaling) {
    extended_vector::scaling<double, 4>();
}

CH_TEST(functional_vector_double_n4_component_product) {
    extended_vector::component_product<double, 4>();
}

CH_TEST(functional_vector_double_n4_dot_reference) {
    extended_vector::dot_reference<double, 4>();
}

CH_TEST(functional_vector_double_n4_normalize_reference) {
    extended_vector::normalize_reference<double, 4>();
}

CH_TEST(functional_vector_double_n4_projection_residual) {
    extended_vector::projection_residual<double, 4>();
}

CH_TEST(functional_vector_double_n4_angle_invariants) {
    extended_vector::angle_invariants<double, 4>();
}

CH_TEST(functional_vector_double_n4_length_extremes) {
    extended_vector::length_extremes<double, 4>();
}

CH_TEST(functional_vector_double_n4_packed_storage) {
    extended_vector::packed_storage<double, 4>();
}

CH_TEST(functional_vector_double_n8_addition) {
    extended_vector::addition<double, 8>();
}

CH_TEST(functional_vector_double_n8_subtraction) {
    extended_vector::subtraction<double, 8>();
}

CH_TEST(functional_vector_double_n8_scaling) {
    extended_vector::scaling<double, 8>();
}

CH_TEST(functional_vector_double_n8_component_product) {
    extended_vector::component_product<double, 8>();
}

CH_TEST(functional_vector_double_n8_dot_reference) {
    extended_vector::dot_reference<double, 8>();
}

CH_TEST(functional_vector_double_n8_normalize_reference) {
    extended_vector::normalize_reference<double, 8>();
}

CH_TEST(functional_vector_double_n8_projection_residual) {
    extended_vector::projection_residual<double, 8>();
}

CH_TEST(functional_vector_double_n8_angle_invariants) {
    extended_vector::angle_invariants<double, 8>();
}

CH_TEST(functional_vector_double_n8_length_extremes) {
    extended_vector::length_extremes<double, 8>();
}

CH_TEST(functional_vector_double_n8_packed_storage) {
    extended_vector::packed_storage<double, 8>();
}

CH_TEST(functional_vector_double_n16_addition) {
    extended_vector::addition<double, 16>();
}

CH_TEST(functional_vector_double_n16_subtraction) {
    extended_vector::subtraction<double, 16>();
}

CH_TEST(functional_vector_double_n16_scaling) {
    extended_vector::scaling<double, 16>();
}

CH_TEST(functional_vector_double_n16_component_product) {
    extended_vector::component_product<double, 16>();
}

CH_TEST(functional_vector_double_n16_dot_reference) {
    extended_vector::dot_reference<double, 16>();
}

CH_TEST(functional_vector_double_n16_normalize_reference) {
    extended_vector::normalize_reference<double, 16>();
}

CH_TEST(functional_vector_double_n16_projection_residual) {
    extended_vector::projection_residual<double, 16>();
}

CH_TEST(functional_vector_double_n16_angle_invariants) {
    extended_vector::angle_invariants<double, 16>();
}

CH_TEST(functional_vector_double_n16_length_extremes) {
    extended_vector::length_extremes<double, 16>();
}

CH_TEST(functional_vector_double_n16_packed_storage) {
    extended_vector::packed_storage<double, 16>();
}
