// Generated by scripts/generate_extended_tests.py; edit the scenario table there.
// clang-format off
#include "extended/matrix_cases.hpp"

CH_TEST(functional_matrix_float_n1_product_oracle) {
    extended_matrix::product_oracle<float, 1>();
}

CH_TEST(functional_matrix_float_n1_transpose_contract) {
    extended_matrix::transpose_contract<float, 1>();
}

CH_TEST(functional_matrix_float_n1_arithmetic) {
    extended_matrix::arithmetic<float, 1>();
}

CH_TEST(functional_matrix_float_n1_triangular_determinant) {
    extended_matrix::triangular_determinant<float, 1>();
}

CH_TEST(functional_matrix_float_n1_solve_known_solution) {
    extended_matrix::solve_known_solution<float, 1>();
}

CH_TEST(functional_matrix_float_n1_multiple_rhs) {
    extended_matrix::multiple_rhs<float, 1>();
}

CH_TEST(functional_matrix_float_n1_two_sided_inverse) {
    extended_matrix::two_sided_inverse<float, 1>();
}

CH_TEST(functional_matrix_float_n1_small_scale_lu) {
    extended_matrix::small_scale_lu<float, 1>();
}

CH_TEST(functional_matrix_float_n1_qr_reconstruction) {
    extended_matrix::qr_reconstruction<float, 1>();
}

CH_TEST(functional_matrix_float_n1_cholesky_reconstruction) {
    extended_matrix::cholesky_reconstruction<float, 1>();
}

CH_TEST(functional_matrix_float_n1_eigen_residuals) {
    extended_matrix::eigen_residuals<float, 1>();
}

CH_TEST(functional_matrix_float_n1_self_assignment) {
    extended_matrix::self_assignment<float, 1>();
}

CH_TEST(functional_matrix_float_n2_product_oracle) {
    extended_matrix::product_oracle<float, 2>();
}

CH_TEST(functional_matrix_float_n2_transpose_contract) {
    extended_matrix::transpose_contract<float, 2>();
}

CH_TEST(functional_matrix_float_n2_arithmetic) {
    extended_matrix::arithmetic<float, 2>();
}

CH_TEST(functional_matrix_float_n2_triangular_determinant) {
    extended_matrix::triangular_determinant<float, 2>();
}

CH_TEST(functional_matrix_float_n2_solve_known_solution) {
    extended_matrix::solve_known_solution<float, 2>();
}

CH_TEST(functional_matrix_float_n2_multiple_rhs) {
    extended_matrix::multiple_rhs<float, 2>();
}

CH_TEST(functional_matrix_float_n2_two_sided_inverse) {
    extended_matrix::two_sided_inverse<float, 2>();
}

CH_TEST(functional_matrix_float_n2_small_scale_lu) {
    extended_matrix::small_scale_lu<float, 2>();
}

CH_TEST(functional_matrix_float_n2_qr_reconstruction) {
    extended_matrix::qr_reconstruction<float, 2>();
}

CH_TEST(functional_matrix_float_n2_cholesky_reconstruction) {
    extended_matrix::cholesky_reconstruction<float, 2>();
}

CH_TEST(functional_matrix_float_n2_eigen_residuals) {
    extended_matrix::eigen_residuals<float, 2>();
}

CH_TEST(functional_matrix_float_n2_self_assignment) {
    extended_matrix::self_assignment<float, 2>();
}

CH_TEST(functional_matrix_float_n3_product_oracle) {
    extended_matrix::product_oracle<float, 3>();
}

CH_TEST(functional_matrix_float_n3_transpose_contract) {
    extended_matrix::transpose_contract<float, 3>();
}

CH_TEST(functional_matrix_float_n3_arithmetic) {
    extended_matrix::arithmetic<float, 3>();
}

CH_TEST(functional_matrix_float_n3_triangular_determinant) {
    extended_matrix::triangular_determinant<float, 3>();
}

CH_TEST(functional_matrix_float_n3_solve_known_solution) {
    extended_matrix::solve_known_solution<float, 3>();
}

CH_TEST(functional_matrix_float_n3_multiple_rhs) {
    extended_matrix::multiple_rhs<float, 3>();
}

CH_TEST(functional_matrix_float_n3_two_sided_inverse) {
    extended_matrix::two_sided_inverse<float, 3>();
}

CH_TEST(functional_matrix_float_n3_small_scale_lu) {
    extended_matrix::small_scale_lu<float, 3>();
}

CH_TEST(functional_matrix_float_n3_qr_reconstruction) {
    extended_matrix::qr_reconstruction<float, 3>();
}

CH_TEST(functional_matrix_float_n3_cholesky_reconstruction) {
    extended_matrix::cholesky_reconstruction<float, 3>();
}

CH_TEST(functional_matrix_float_n3_eigen_residuals) {
    extended_matrix::eigen_residuals<float, 3>();
}

CH_TEST(functional_matrix_float_n3_self_assignment) {
    extended_matrix::self_assignment<float, 3>();
}

CH_TEST(functional_matrix_float_n4_product_oracle) {
    extended_matrix::product_oracle<float, 4>();
}

CH_TEST(functional_matrix_float_n4_transpose_contract) {
    extended_matrix::transpose_contract<float, 4>();
}

CH_TEST(functional_matrix_float_n4_arithmetic) {
    extended_matrix::arithmetic<float, 4>();
}

CH_TEST(functional_matrix_float_n4_triangular_determinant) {
    extended_matrix::triangular_determinant<float, 4>();
}

CH_TEST(functional_matrix_float_n4_solve_known_solution) {
    extended_matrix::solve_known_solution<float, 4>();
}

CH_TEST(functional_matrix_float_n4_multiple_rhs) {
    extended_matrix::multiple_rhs<float, 4>();
}

CH_TEST(functional_matrix_float_n4_two_sided_inverse) {
    extended_matrix::two_sided_inverse<float, 4>();
}

CH_TEST(functional_matrix_float_n4_small_scale_lu) {
    extended_matrix::small_scale_lu<float, 4>();
}

CH_TEST(functional_matrix_float_n4_qr_reconstruction) {
    extended_matrix::qr_reconstruction<float, 4>();
}

CH_TEST(functional_matrix_float_n4_cholesky_reconstruction) {
    extended_matrix::cholesky_reconstruction<float, 4>();
}

CH_TEST(functional_matrix_float_n4_eigen_residuals) {
    extended_matrix::eigen_residuals<float, 4>();
}

CH_TEST(functional_matrix_float_n4_self_assignment) {
    extended_matrix::self_assignment<float, 4>();
}

CH_TEST(functional_matrix_float_n8_product_oracle) {
    extended_matrix::product_oracle<float, 8>();
}

CH_TEST(functional_matrix_float_n8_transpose_contract) {
    extended_matrix::transpose_contract<float, 8>();
}

CH_TEST(functional_matrix_float_n8_arithmetic) {
    extended_matrix::arithmetic<float, 8>();
}

CH_TEST(functional_matrix_float_n8_triangular_determinant) {
    extended_matrix::triangular_determinant<float, 8>();
}

CH_TEST(functional_matrix_float_n8_solve_known_solution) {
    extended_matrix::solve_known_solution<float, 8>();
}

CH_TEST(functional_matrix_float_n8_multiple_rhs) {
    extended_matrix::multiple_rhs<float, 8>();
}

CH_TEST(functional_matrix_float_n8_two_sided_inverse) {
    extended_matrix::two_sided_inverse<float, 8>();
}

CH_TEST(functional_matrix_float_n8_small_scale_lu) {
    extended_matrix::small_scale_lu<float, 8>();
}

CH_TEST(functional_matrix_float_n8_qr_reconstruction) {
    extended_matrix::qr_reconstruction<float, 8>();
}

CH_TEST(functional_matrix_float_n8_cholesky_reconstruction) {
    extended_matrix::cholesky_reconstruction<float, 8>();
}

CH_TEST(functional_matrix_float_n8_eigen_residuals) {
    extended_matrix::eigen_residuals<float, 8>();
}

CH_TEST(functional_matrix_float_n8_self_assignment) {
    extended_matrix::self_assignment<float, 8>();
}

CH_TEST(functional_matrix_double_n1_product_oracle) {
    extended_matrix::product_oracle<double, 1>();
}

CH_TEST(functional_matrix_double_n1_transpose_contract) {
    extended_matrix::transpose_contract<double, 1>();
}

CH_TEST(functional_matrix_double_n1_arithmetic) {
    extended_matrix::arithmetic<double, 1>();
}

CH_TEST(functional_matrix_double_n1_triangular_determinant) {
    extended_matrix::triangular_determinant<double, 1>();
}

CH_TEST(functional_matrix_double_n1_solve_known_solution) {
    extended_matrix::solve_known_solution<double, 1>();
}

CH_TEST(functional_matrix_double_n1_multiple_rhs) {
    extended_matrix::multiple_rhs<double, 1>();
}

CH_TEST(functional_matrix_double_n1_two_sided_inverse) {
    extended_matrix::two_sided_inverse<double, 1>();
}

CH_TEST(functional_matrix_double_n1_small_scale_lu) {
    extended_matrix::small_scale_lu<double, 1>();
}

CH_TEST(functional_matrix_double_n1_qr_reconstruction) {
    extended_matrix::qr_reconstruction<double, 1>();
}

CH_TEST(functional_matrix_double_n1_cholesky_reconstruction) {
    extended_matrix::cholesky_reconstruction<double, 1>();
}

CH_TEST(functional_matrix_double_n1_eigen_residuals) {
    extended_matrix::eigen_residuals<double, 1>();
}

CH_TEST(functional_matrix_double_n1_self_assignment) {
    extended_matrix::self_assignment<double, 1>();
}

CH_TEST(functional_matrix_double_n2_product_oracle) {
    extended_matrix::product_oracle<double, 2>();
}

CH_TEST(functional_matrix_double_n2_transpose_contract) {
    extended_matrix::transpose_contract<double, 2>();
}

CH_TEST(functional_matrix_double_n2_arithmetic) {
    extended_matrix::arithmetic<double, 2>();
}

CH_TEST(functional_matrix_double_n2_triangular_determinant) {
    extended_matrix::triangular_determinant<double, 2>();
}

CH_TEST(functional_matrix_double_n2_solve_known_solution) {
    extended_matrix::solve_known_solution<double, 2>();
}

CH_TEST(functional_matrix_double_n2_multiple_rhs) {
    extended_matrix::multiple_rhs<double, 2>();
}

CH_TEST(functional_matrix_double_n2_two_sided_inverse) {
    extended_matrix::two_sided_inverse<double, 2>();
}

CH_TEST(functional_matrix_double_n2_small_scale_lu) {
    extended_matrix::small_scale_lu<double, 2>();
}

CH_TEST(functional_matrix_double_n2_qr_reconstruction) {
    extended_matrix::qr_reconstruction<double, 2>();
}

CH_TEST(functional_matrix_double_n2_cholesky_reconstruction) {
    extended_matrix::cholesky_reconstruction<double, 2>();
}

CH_TEST(functional_matrix_double_n2_eigen_residuals) {
    extended_matrix::eigen_residuals<double, 2>();
}

CH_TEST(functional_matrix_double_n2_self_assignment) {
    extended_matrix::self_assignment<double, 2>();
}

CH_TEST(functional_matrix_double_n3_product_oracle) {
    extended_matrix::product_oracle<double, 3>();
}

CH_TEST(functional_matrix_double_n3_transpose_contract) {
    extended_matrix::transpose_contract<double, 3>();
}

CH_TEST(functional_matrix_double_n3_arithmetic) {
    extended_matrix::arithmetic<double, 3>();
}

CH_TEST(functional_matrix_double_n3_triangular_determinant) {
    extended_matrix::triangular_determinant<double, 3>();
}

CH_TEST(functional_matrix_double_n3_solve_known_solution) {
    extended_matrix::solve_known_solution<double, 3>();
}

CH_TEST(functional_matrix_double_n3_multiple_rhs) {
    extended_matrix::multiple_rhs<double, 3>();
}

CH_TEST(functional_matrix_double_n3_two_sided_inverse) {
    extended_matrix::two_sided_inverse<double, 3>();
}

CH_TEST(functional_matrix_double_n3_small_scale_lu) {
    extended_matrix::small_scale_lu<double, 3>();
}

CH_TEST(functional_matrix_double_n3_qr_reconstruction) {
    extended_matrix::qr_reconstruction<double, 3>();
}

CH_TEST(functional_matrix_double_n3_cholesky_reconstruction) {
    extended_matrix::cholesky_reconstruction<double, 3>();
}

CH_TEST(functional_matrix_double_n3_eigen_residuals) {
    extended_matrix::eigen_residuals<double, 3>();
}

CH_TEST(functional_matrix_double_n3_self_assignment) {
    extended_matrix::self_assignment<double, 3>();
}

CH_TEST(functional_matrix_double_n4_product_oracle) {
    extended_matrix::product_oracle<double, 4>();
}

CH_TEST(functional_matrix_double_n4_transpose_contract) {
    extended_matrix::transpose_contract<double, 4>();
}

CH_TEST(functional_matrix_double_n4_arithmetic) {
    extended_matrix::arithmetic<double, 4>();
}

CH_TEST(functional_matrix_double_n4_triangular_determinant) {
    extended_matrix::triangular_determinant<double, 4>();
}

CH_TEST(functional_matrix_double_n4_solve_known_solution) {
    extended_matrix::solve_known_solution<double, 4>();
}

CH_TEST(functional_matrix_double_n4_multiple_rhs) {
    extended_matrix::multiple_rhs<double, 4>();
}

CH_TEST(functional_matrix_double_n4_two_sided_inverse) {
    extended_matrix::two_sided_inverse<double, 4>();
}

CH_TEST(functional_matrix_double_n4_small_scale_lu) {
    extended_matrix::small_scale_lu<double, 4>();
}

CH_TEST(functional_matrix_double_n4_qr_reconstruction) {
    extended_matrix::qr_reconstruction<double, 4>();
}

CH_TEST(functional_matrix_double_n4_cholesky_reconstruction) {
    extended_matrix::cholesky_reconstruction<double, 4>();
}

CH_TEST(functional_matrix_double_n4_eigen_residuals) {
    extended_matrix::eigen_residuals<double, 4>();
}

CH_TEST(functional_matrix_double_n4_self_assignment) {
    extended_matrix::self_assignment<double, 4>();
}

CH_TEST(functional_matrix_double_n8_product_oracle) {
    extended_matrix::product_oracle<double, 8>();
}

CH_TEST(functional_matrix_double_n8_transpose_contract) {
    extended_matrix::transpose_contract<double, 8>();
}

CH_TEST(functional_matrix_double_n8_arithmetic) {
    extended_matrix::arithmetic<double, 8>();
}

CH_TEST(functional_matrix_double_n8_triangular_determinant) {
    extended_matrix::triangular_determinant<double, 8>();
}

CH_TEST(functional_matrix_double_n8_solve_known_solution) {
    extended_matrix::solve_known_solution<double, 8>();
}

CH_TEST(functional_matrix_double_n8_multiple_rhs) {
    extended_matrix::multiple_rhs<double, 8>();
}

CH_TEST(functional_matrix_double_n8_two_sided_inverse) {
    extended_matrix::two_sided_inverse<double, 8>();
}

CH_TEST(functional_matrix_double_n8_small_scale_lu) {
    extended_matrix::small_scale_lu<double, 8>();
}

CH_TEST(functional_matrix_double_n8_qr_reconstruction) {
    extended_matrix::qr_reconstruction<double, 8>();
}

CH_TEST(functional_matrix_double_n8_cholesky_reconstruction) {
    extended_matrix::cholesky_reconstruction<double, 8>();
}

CH_TEST(functional_matrix_double_n8_eigen_residuals) {
    extended_matrix::eigen_residuals<double, 8>();
}

CH_TEST(functional_matrix_double_n8_self_assignment) {
    extended_matrix::self_assignment<double, 8>();
}
