// Generated by scripts/generate_extended_tests.py; edit the scenario table there.
// clang-format off
#include "extended/batch_cases.hpp"

CH_TEST(safety_batch_float_points_size0) {
    extended_batch::guarded_contract<float, 0, 0>();
}

CH_TEST(safety_batch_float_points_size1) {
    extended_batch::guarded_contract<float, 0, 1>();
}

CH_TEST(safety_batch_float_points_size2) {
    extended_batch::guarded_contract<float, 0, 2>();
}

CH_TEST(safety_batch_float_points_size3) {
    extended_batch::guarded_contract<float, 0, 3>();
}

CH_TEST(safety_batch_float_points_size4) {
    extended_batch::guarded_contract<float, 0, 4>();
}

CH_TEST(safety_batch_float_points_size5) {
    extended_batch::guarded_contract<float, 0, 5>();
}

CH_TEST(safety_batch_float_points_size7) {
    extended_batch::guarded_contract<float, 0, 7>();
}

CH_TEST(safety_batch_float_points_size8) {
    extended_batch::guarded_contract<float, 0, 8>();
}

CH_TEST(safety_batch_float_points_size9) {
    extended_batch::guarded_contract<float, 0, 9>();
}

CH_TEST(safety_batch_float_points_size15) {
    extended_batch::guarded_contract<float, 0, 15>();
}

CH_TEST(safety_batch_float_points_size16) {
    extended_batch::guarded_contract<float, 0, 16>();
}

CH_TEST(safety_batch_float_points_size17) {
    extended_batch::guarded_contract<float, 0, 17>();
}

CH_TEST(safety_batch_float_vectors_size0) {
    extended_batch::guarded_contract<float, 1, 0>();
}

CH_TEST(safety_batch_float_vectors_size1) {
    extended_batch::guarded_contract<float, 1, 1>();
}

CH_TEST(safety_batch_float_vectors_size2) {
    extended_batch::guarded_contract<float, 1, 2>();
}

CH_TEST(safety_batch_float_vectors_size3) {
    extended_batch::guarded_contract<float, 1, 3>();
}

CH_TEST(safety_batch_float_vectors_size4) {
    extended_batch::guarded_contract<float, 1, 4>();
}

CH_TEST(safety_batch_float_vectors_size5) {
    extended_batch::guarded_contract<float, 1, 5>();
}

CH_TEST(safety_batch_float_vectors_size7) {
    extended_batch::guarded_contract<float, 1, 7>();
}

CH_TEST(safety_batch_float_vectors_size8) {
    extended_batch::guarded_contract<float, 1, 8>();
}

CH_TEST(safety_batch_float_vectors_size9) {
    extended_batch::guarded_contract<float, 1, 9>();
}

CH_TEST(safety_batch_float_vectors_size15) {
    extended_batch::guarded_contract<float, 1, 15>();
}

CH_TEST(safety_batch_float_vectors_size16) {
    extended_batch::guarded_contract<float, 1, 16>();
}

CH_TEST(safety_batch_float_vectors_size17) {
    extended_batch::guarded_contract<float, 1, 17>();
}

CH_TEST(safety_batch_float_rotation_size0) {
    extended_batch::guarded_contract<float, 2, 0>();
}

CH_TEST(safety_batch_float_rotation_size1) {
    extended_batch::guarded_contract<float, 2, 1>();
}

CH_TEST(safety_batch_float_rotation_size2) {
    extended_batch::guarded_contract<float, 2, 2>();
}

CH_TEST(safety_batch_float_rotation_size3) {
    extended_batch::guarded_contract<float, 2, 3>();
}

CH_TEST(safety_batch_float_rotation_size4) {
    extended_batch::guarded_contract<float, 2, 4>();
}

CH_TEST(safety_batch_float_rotation_size5) {
    extended_batch::guarded_contract<float, 2, 5>();
}

CH_TEST(safety_batch_float_rotation_size7) {
    extended_batch::guarded_contract<float, 2, 7>();
}

CH_TEST(safety_batch_float_rotation_size8) {
    extended_batch::guarded_contract<float, 2, 8>();
}

CH_TEST(safety_batch_float_rotation_size9) {
    extended_batch::guarded_contract<float, 2, 9>();
}

CH_TEST(safety_batch_float_rotation_size15) {
    extended_batch::guarded_contract<float, 2, 15>();
}

CH_TEST(safety_batch_float_rotation_size16) {
    extended_batch::guarded_contract<float, 2, 16>();
}

CH_TEST(safety_batch_float_rotation_size17) {
    extended_batch::guarded_contract<float, 2, 17>();
}

CH_TEST(safety_batch_float_dot_size0) {
    extended_batch::guarded_contract<float, 3, 0>();
}

CH_TEST(safety_batch_float_dot_size1) {
    extended_batch::guarded_contract<float, 3, 1>();
}

CH_TEST(safety_batch_float_dot_size2) {
    extended_batch::guarded_contract<float, 3, 2>();
}

CH_TEST(safety_batch_float_dot_size3) {
    extended_batch::guarded_contract<float, 3, 3>();
}

CH_TEST(safety_batch_float_dot_size4) {
    extended_batch::guarded_contract<float, 3, 4>();
}

CH_TEST(safety_batch_float_dot_size5) {
    extended_batch::guarded_contract<float, 3, 5>();
}

CH_TEST(safety_batch_float_dot_size7) {
    extended_batch::guarded_contract<float, 3, 7>();
}

CH_TEST(safety_batch_float_dot_size8) {
    extended_batch::guarded_contract<float, 3, 8>();
}

CH_TEST(safety_batch_float_dot_size9) {
    extended_batch::guarded_contract<float, 3, 9>();
}

CH_TEST(safety_batch_float_dot_size15) {
    extended_batch::guarded_contract<float, 3, 15>();
}

CH_TEST(safety_batch_float_dot_size16) {
    extended_batch::guarded_contract<float, 3, 16>();
}

CH_TEST(safety_batch_float_dot_size17) {
    extended_batch::guarded_contract<float, 3, 17>();
}

CH_TEST(safety_batch_float_cross_size0) {
    extended_batch::guarded_contract<float, 4, 0>();
}

CH_TEST(safety_batch_float_cross_size1) {
    extended_batch::guarded_contract<float, 4, 1>();
}

CH_TEST(safety_batch_float_cross_size2) {
    extended_batch::guarded_contract<float, 4, 2>();
}

CH_TEST(safety_batch_float_cross_size3) {
    extended_batch::guarded_contract<float, 4, 3>();
}

CH_TEST(safety_batch_float_cross_size4) {
    extended_batch::guarded_contract<float, 4, 4>();
}

CH_TEST(safety_batch_float_cross_size5) {
    extended_batch::guarded_contract<float, 4, 5>();
}

CH_TEST(safety_batch_float_cross_size7) {
    extended_batch::guarded_contract<float, 4, 7>();
}

CH_TEST(safety_batch_float_cross_size8) {
    extended_batch::guarded_contract<float, 4, 8>();
}

CH_TEST(safety_batch_float_cross_size9) {
    extended_batch::guarded_contract<float, 4, 9>();
}

CH_TEST(safety_batch_float_cross_size15) {
    extended_batch::guarded_contract<float, 4, 15>();
}

CH_TEST(safety_batch_float_cross_size16) {
    extended_batch::guarded_contract<float, 4, 16>();
}

CH_TEST(safety_batch_float_cross_size17) {
    extended_batch::guarded_contract<float, 4, 17>();
}

CH_TEST(safety_batch_float_normalize_size0) {
    extended_batch::guarded_contract<float, 5, 0>();
}

CH_TEST(safety_batch_float_normalize_size1) {
    extended_batch::guarded_contract<float, 5, 1>();
}

CH_TEST(safety_batch_float_normalize_size2) {
    extended_batch::guarded_contract<float, 5, 2>();
}

CH_TEST(safety_batch_float_normalize_size3) {
    extended_batch::guarded_contract<float, 5, 3>();
}

CH_TEST(safety_batch_float_normalize_size4) {
    extended_batch::guarded_contract<float, 5, 4>();
}

CH_TEST(safety_batch_float_normalize_size5) {
    extended_batch::guarded_contract<float, 5, 5>();
}

CH_TEST(safety_batch_float_normalize_size7) {
    extended_batch::guarded_contract<float, 5, 7>();
}

CH_TEST(safety_batch_float_normalize_size8) {
    extended_batch::guarded_contract<float, 5, 8>();
}

CH_TEST(safety_batch_float_normalize_size9) {
    extended_batch::guarded_contract<float, 5, 9>();
}

CH_TEST(safety_batch_float_normalize_size15) {
    extended_batch::guarded_contract<float, 5, 15>();
}

CH_TEST(safety_batch_float_normalize_size16) {
    extended_batch::guarded_contract<float, 5, 16>();
}

CH_TEST(safety_batch_float_normalize_size17) {
    extended_batch::guarded_contract<float, 5, 17>();
}

CH_TEST(safety_batch_double_points_size0) {
    extended_batch::guarded_contract<double, 0, 0>();
}

CH_TEST(safety_batch_double_points_size1) {
    extended_batch::guarded_contract<double, 0, 1>();
}

CH_TEST(safety_batch_double_points_size2) {
    extended_batch::guarded_contract<double, 0, 2>();
}

CH_TEST(safety_batch_double_points_size3) {
    extended_batch::guarded_contract<double, 0, 3>();
}

CH_TEST(safety_batch_double_points_size4) {
    extended_batch::guarded_contract<double, 0, 4>();
}

CH_TEST(safety_batch_double_points_size5) {
    extended_batch::guarded_contract<double, 0, 5>();
}

CH_TEST(safety_batch_double_points_size7) {
    extended_batch::guarded_contract<double, 0, 7>();
}

CH_TEST(safety_batch_double_points_size8) {
    extended_batch::guarded_contract<double, 0, 8>();
}

CH_TEST(safety_batch_double_points_size9) {
    extended_batch::guarded_contract<double, 0, 9>();
}

CH_TEST(safety_batch_double_points_size15) {
    extended_batch::guarded_contract<double, 0, 15>();
}

CH_TEST(safety_batch_double_points_size16) {
    extended_batch::guarded_contract<double, 0, 16>();
}

CH_TEST(safety_batch_double_points_size17) {
    extended_batch::guarded_contract<double, 0, 17>();
}

CH_TEST(safety_batch_double_vectors_size0) {
    extended_batch::guarded_contract<double, 1, 0>();
}

CH_TEST(safety_batch_double_vectors_size1) {
    extended_batch::guarded_contract<double, 1, 1>();
}

CH_TEST(safety_batch_double_vectors_size2) {
    extended_batch::guarded_contract<double, 1, 2>();
}

CH_TEST(safety_batch_double_vectors_size3) {
    extended_batch::guarded_contract<double, 1, 3>();
}

CH_TEST(safety_batch_double_vectors_size4) {
    extended_batch::guarded_contract<double, 1, 4>();
}

CH_TEST(safety_batch_double_vectors_size5) {
    extended_batch::guarded_contract<double, 1, 5>();
}

CH_TEST(safety_batch_double_vectors_size7) {
    extended_batch::guarded_contract<double, 1, 7>();
}

CH_TEST(safety_batch_double_vectors_size8) {
    extended_batch::guarded_contract<double, 1, 8>();
}

CH_TEST(safety_batch_double_vectors_size9) {
    extended_batch::guarded_contract<double, 1, 9>();
}

CH_TEST(safety_batch_double_vectors_size15) {
    extended_batch::guarded_contract<double, 1, 15>();
}

CH_TEST(safety_batch_double_vectors_size16) {
    extended_batch::guarded_contract<double, 1, 16>();
}

CH_TEST(safety_batch_double_vectors_size17) {
    extended_batch::guarded_contract<double, 1, 17>();
}

CH_TEST(safety_batch_double_rotation_size0) {
    extended_batch::guarded_contract<double, 2, 0>();
}

CH_TEST(safety_batch_double_rotation_size1) {
    extended_batch::guarded_contract<double, 2, 1>();
}

CH_TEST(safety_batch_double_rotation_size2) {
    extended_batch::guarded_contract<double, 2, 2>();
}

CH_TEST(safety_batch_double_rotation_size3) {
    extended_batch::guarded_contract<double, 2, 3>();
}

CH_TEST(safety_batch_double_rotation_size4) {
    extended_batch::guarded_contract<double, 2, 4>();
}

CH_TEST(safety_batch_double_rotation_size5) {
    extended_batch::guarded_contract<double, 2, 5>();
}

CH_TEST(safety_batch_double_rotation_size7) {
    extended_batch::guarded_contract<double, 2, 7>();
}

CH_TEST(safety_batch_double_rotation_size8) {
    extended_batch::guarded_contract<double, 2, 8>();
}

CH_TEST(safety_batch_double_rotation_size9) {
    extended_batch::guarded_contract<double, 2, 9>();
}

CH_TEST(safety_batch_double_rotation_size15) {
    extended_batch::guarded_contract<double, 2, 15>();
}

CH_TEST(safety_batch_double_rotation_size16) {
    extended_batch::guarded_contract<double, 2, 16>();
}

CH_TEST(safety_batch_double_rotation_size17) {
    extended_batch::guarded_contract<double, 2, 17>();
}

CH_TEST(safety_batch_double_dot_size0) {
    extended_batch::guarded_contract<double, 3, 0>();
}

CH_TEST(safety_batch_double_dot_size1) {
    extended_batch::guarded_contract<double, 3, 1>();
}

CH_TEST(safety_batch_double_dot_size2) {
    extended_batch::guarded_contract<double, 3, 2>();
}

CH_TEST(safety_batch_double_dot_size3) {
    extended_batch::guarded_contract<double, 3, 3>();
}

CH_TEST(safety_batch_double_dot_size4) {
    extended_batch::guarded_contract<double, 3, 4>();
}

CH_TEST(safety_batch_double_dot_size5) {
    extended_batch::guarded_contract<double, 3, 5>();
}

CH_TEST(safety_batch_double_dot_size7) {
    extended_batch::guarded_contract<double, 3, 7>();
}

CH_TEST(safety_batch_double_dot_size8) {
    extended_batch::guarded_contract<double, 3, 8>();
}

CH_TEST(safety_batch_double_dot_size9) {
    extended_batch::guarded_contract<double, 3, 9>();
}

CH_TEST(safety_batch_double_dot_size15) {
    extended_batch::guarded_contract<double, 3, 15>();
}

CH_TEST(safety_batch_double_dot_size16) {
    extended_batch::guarded_contract<double, 3, 16>();
}

CH_TEST(safety_batch_double_dot_size17) {
    extended_batch::guarded_contract<double, 3, 17>();
}

CH_TEST(safety_batch_double_cross_size0) {
    extended_batch::guarded_contract<double, 4, 0>();
}

CH_TEST(safety_batch_double_cross_size1) {
    extended_batch::guarded_contract<double, 4, 1>();
}

CH_TEST(safety_batch_double_cross_size2) {
    extended_batch::guarded_contract<double, 4, 2>();
}

CH_TEST(safety_batch_double_cross_size3) {
    extended_batch::guarded_contract<double, 4, 3>();
}

CH_TEST(safety_batch_double_cross_size4) {
    extended_batch::guarded_contract<double, 4, 4>();
}

CH_TEST(safety_batch_double_cross_size5) {
    extended_batch::guarded_contract<double, 4, 5>();
}

CH_TEST(safety_batch_double_cross_size7) {
    extended_batch::guarded_contract<double, 4, 7>();
}

CH_TEST(safety_batch_double_cross_size8) {
    extended_batch::guarded_contract<double, 4, 8>();
}

CH_TEST(safety_batch_double_cross_size9) {
    extended_batch::guarded_contract<double, 4, 9>();
}

CH_TEST(safety_batch_double_cross_size15) {
    extended_batch::guarded_contract<double, 4, 15>();
}

CH_TEST(safety_batch_double_cross_size16) {
    extended_batch::guarded_contract<double, 4, 16>();
}

CH_TEST(safety_batch_double_cross_size17) {
    extended_batch::guarded_contract<double, 4, 17>();
}

CH_TEST(safety_batch_double_normalize_size0) {
    extended_batch::guarded_contract<double, 5, 0>();
}

CH_TEST(safety_batch_double_normalize_size1) {
    extended_batch::guarded_contract<double, 5, 1>();
}

CH_TEST(safety_batch_double_normalize_size2) {
    extended_batch::guarded_contract<double, 5, 2>();
}

CH_TEST(safety_batch_double_normalize_size3) {
    extended_batch::guarded_contract<double, 5, 3>();
}

CH_TEST(safety_batch_double_normalize_size4) {
    extended_batch::guarded_contract<double, 5, 4>();
}

CH_TEST(safety_batch_double_normalize_size5) {
    extended_batch::guarded_contract<double, 5, 5>();
}

CH_TEST(safety_batch_double_normalize_size7) {
    extended_batch::guarded_contract<double, 5, 7>();
}

CH_TEST(safety_batch_double_normalize_size8) {
    extended_batch::guarded_contract<double, 5, 8>();
}

CH_TEST(safety_batch_double_normalize_size9) {
    extended_batch::guarded_contract<double, 5, 9>();
}

CH_TEST(safety_batch_double_normalize_size15) {
    extended_batch::guarded_contract<double, 5, 15>();
}

CH_TEST(safety_batch_double_normalize_size16) {
    extended_batch::guarded_contract<double, 5, 16>();
}

CH_TEST(safety_batch_double_normalize_size17) {
    extended_batch::guarded_contract<double, 5, 17>();
}
