// Generated by scripts/generate_extended_tests.py; edit the scenario table there.
// clang-format off
#include "extended/rotation_cases.hpp"

CH_TEST(functional_rotation_float_axis0_angle0_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 0, 0>();
}

CH_TEST(functional_rotation_float_axis0_angle0_between_directions) {
    extended_rotation::between_directions<float, 0, 0>();
}

CH_TEST(functional_rotation_float_axis0_angle0_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 0, 0>();
}

CH_TEST(functional_rotation_float_axis0_angle1_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 0, 1>();
}

CH_TEST(functional_rotation_float_axis0_angle1_between_directions) {
    extended_rotation::between_directions<float, 0, 1>();
}

CH_TEST(functional_rotation_float_axis0_angle1_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 0, 1>();
}

CH_TEST(functional_rotation_float_axis0_angle2_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 0, 2>();
}

CH_TEST(functional_rotation_float_axis0_angle2_between_directions) {
    extended_rotation::between_directions<float, 0, 2>();
}

CH_TEST(functional_rotation_float_axis0_angle2_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 0, 2>();
}

CH_TEST(functional_rotation_float_axis0_angle3_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 0, 3>();
}

CH_TEST(functional_rotation_float_axis0_angle3_between_directions) {
    extended_rotation::between_directions<float, 0, 3>();
}

CH_TEST(functional_rotation_float_axis0_angle3_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 0, 3>();
}

CH_TEST(functional_rotation_float_axis1_angle0_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 1, 0>();
}

CH_TEST(functional_rotation_float_axis1_angle0_between_directions) {
    extended_rotation::between_directions<float, 1, 0>();
}

CH_TEST(functional_rotation_float_axis1_angle0_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 1, 0>();
}

CH_TEST(functional_rotation_float_axis1_angle1_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 1, 1>();
}

CH_TEST(functional_rotation_float_axis1_angle1_between_directions) {
    extended_rotation::between_directions<float, 1, 1>();
}

CH_TEST(functional_rotation_float_axis1_angle1_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 1, 1>();
}

CH_TEST(functional_rotation_float_axis1_angle2_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 1, 2>();
}

CH_TEST(functional_rotation_float_axis1_angle2_between_directions) {
    extended_rotation::between_directions<float, 1, 2>();
}

CH_TEST(functional_rotation_float_axis1_angle2_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 1, 2>();
}

CH_TEST(functional_rotation_float_axis1_angle3_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 1, 3>();
}

CH_TEST(functional_rotation_float_axis1_angle3_between_directions) {
    extended_rotation::between_directions<float, 1, 3>();
}

CH_TEST(functional_rotation_float_axis1_angle3_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 1, 3>();
}

CH_TEST(functional_rotation_float_axis2_angle0_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 2, 0>();
}

CH_TEST(functional_rotation_float_axis2_angle0_between_directions) {
    extended_rotation::between_directions<float, 2, 0>();
}

CH_TEST(functional_rotation_float_axis2_angle0_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 2, 0>();
}

CH_TEST(functional_rotation_float_axis2_angle1_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 2, 1>();
}

CH_TEST(functional_rotation_float_axis2_angle1_between_directions) {
    extended_rotation::between_directions<float, 2, 1>();
}

CH_TEST(functional_rotation_float_axis2_angle1_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 2, 1>();
}

CH_TEST(functional_rotation_float_axis2_angle2_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 2, 2>();
}

CH_TEST(functional_rotation_float_axis2_angle2_between_directions) {
    extended_rotation::between_directions<float, 2, 2>();
}

CH_TEST(functional_rotation_float_axis2_angle2_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 2, 2>();
}

CH_TEST(functional_rotation_float_axis2_angle3_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 2, 3>();
}

CH_TEST(functional_rotation_float_axis2_angle3_between_directions) {
    extended_rotation::between_directions<float, 2, 3>();
}

CH_TEST(functional_rotation_float_axis2_angle3_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 2, 3>();
}

CH_TEST(functional_rotation_float_axis3_angle0_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 3, 0>();
}

CH_TEST(functional_rotation_float_axis3_angle0_between_directions) {
    extended_rotation::between_directions<float, 3, 0>();
}

CH_TEST(functional_rotation_float_axis3_angle0_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 3, 0>();
}

CH_TEST(functional_rotation_float_axis3_angle1_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 3, 1>();
}

CH_TEST(functional_rotation_float_axis3_angle1_between_directions) {
    extended_rotation::between_directions<float, 3, 1>();
}

CH_TEST(functional_rotation_float_axis3_angle1_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 3, 1>();
}

CH_TEST(functional_rotation_float_axis3_angle2_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 3, 2>();
}

CH_TEST(functional_rotation_float_axis3_angle2_between_directions) {
    extended_rotation::between_directions<float, 3, 2>();
}

CH_TEST(functional_rotation_float_axis3_angle2_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 3, 2>();
}

CH_TEST(functional_rotation_float_axis3_angle3_rodrigues_reference) {
    extended_rotation::rodrigues_reference<float, 3, 3>();
}

CH_TEST(functional_rotation_float_axis3_angle3_between_directions) {
    extended_rotation::between_directions<float, 3, 3>();
}

CH_TEST(functional_rotation_float_axis3_angle3_interpolation_arc) {
    extended_rotation::interpolation_arc<float, 3, 3>();
}

CH_TEST(functional_rotation_double_axis0_angle0_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 0, 0>();
}

CH_TEST(functional_rotation_double_axis0_angle0_between_directions) {
    extended_rotation::between_directions<double, 0, 0>();
}

CH_TEST(functional_rotation_double_axis0_angle0_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 0, 0>();
}

CH_TEST(functional_rotation_double_axis0_angle1_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 0, 1>();
}

CH_TEST(functional_rotation_double_axis0_angle1_between_directions) {
    extended_rotation::between_directions<double, 0, 1>();
}

CH_TEST(functional_rotation_double_axis0_angle1_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 0, 1>();
}

CH_TEST(functional_rotation_double_axis0_angle2_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 0, 2>();
}

CH_TEST(functional_rotation_double_axis0_angle2_between_directions) {
    extended_rotation::between_directions<double, 0, 2>();
}

CH_TEST(functional_rotation_double_axis0_angle2_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 0, 2>();
}

CH_TEST(functional_rotation_double_axis0_angle3_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 0, 3>();
}

CH_TEST(functional_rotation_double_axis0_angle3_between_directions) {
    extended_rotation::between_directions<double, 0, 3>();
}

CH_TEST(functional_rotation_double_axis0_angle3_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 0, 3>();
}

CH_TEST(functional_rotation_double_axis1_angle0_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 1, 0>();
}

CH_TEST(functional_rotation_double_axis1_angle0_between_directions) {
    extended_rotation::between_directions<double, 1, 0>();
}

CH_TEST(functional_rotation_double_axis1_angle0_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 1, 0>();
}

CH_TEST(functional_rotation_double_axis1_angle1_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 1, 1>();
}

CH_TEST(functional_rotation_double_axis1_angle1_between_directions) {
    extended_rotation::between_directions<double, 1, 1>();
}

CH_TEST(functional_rotation_double_axis1_angle1_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 1, 1>();
}

CH_TEST(functional_rotation_double_axis1_angle2_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 1, 2>();
}

CH_TEST(functional_rotation_double_axis1_angle2_between_directions) {
    extended_rotation::between_directions<double, 1, 2>();
}

CH_TEST(functional_rotation_double_axis1_angle2_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 1, 2>();
}

CH_TEST(functional_rotation_double_axis1_angle3_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 1, 3>();
}

CH_TEST(functional_rotation_double_axis1_angle3_between_directions) {
    extended_rotation::between_directions<double, 1, 3>();
}

CH_TEST(functional_rotation_double_axis1_angle3_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 1, 3>();
}

CH_TEST(functional_rotation_double_axis2_angle0_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 2, 0>();
}

CH_TEST(functional_rotation_double_axis2_angle0_between_directions) {
    extended_rotation::between_directions<double, 2, 0>();
}

CH_TEST(functional_rotation_double_axis2_angle0_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 2, 0>();
}

CH_TEST(functional_rotation_double_axis2_angle1_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 2, 1>();
}

CH_TEST(functional_rotation_double_axis2_angle1_between_directions) {
    extended_rotation::between_directions<double, 2, 1>();
}

CH_TEST(functional_rotation_double_axis2_angle1_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 2, 1>();
}

CH_TEST(functional_rotation_double_axis2_angle2_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 2, 2>();
}

CH_TEST(functional_rotation_double_axis2_angle2_between_directions) {
    extended_rotation::between_directions<double, 2, 2>();
}

CH_TEST(functional_rotation_double_axis2_angle2_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 2, 2>();
}

CH_TEST(functional_rotation_double_axis2_angle3_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 2, 3>();
}

CH_TEST(functional_rotation_double_axis2_angle3_between_directions) {
    extended_rotation::between_directions<double, 2, 3>();
}

CH_TEST(functional_rotation_double_axis2_angle3_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 2, 3>();
}

CH_TEST(functional_rotation_double_axis3_angle0_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 3, 0>();
}

CH_TEST(functional_rotation_double_axis3_angle0_between_directions) {
    extended_rotation::between_directions<double, 3, 0>();
}

CH_TEST(functional_rotation_double_axis3_angle0_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 3, 0>();
}

CH_TEST(functional_rotation_double_axis3_angle1_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 3, 1>();
}

CH_TEST(functional_rotation_double_axis3_angle1_between_directions) {
    extended_rotation::between_directions<double, 3, 1>();
}

CH_TEST(functional_rotation_double_axis3_angle1_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 3, 1>();
}

CH_TEST(functional_rotation_double_axis3_angle2_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 3, 2>();
}

CH_TEST(functional_rotation_double_axis3_angle2_between_directions) {
    extended_rotation::between_directions<double, 3, 2>();
}

CH_TEST(functional_rotation_double_axis3_angle2_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 3, 2>();
}

CH_TEST(functional_rotation_double_axis3_angle3_rodrigues_reference) {
    extended_rotation::rodrigues_reference<double, 3, 3>();
}

CH_TEST(functional_rotation_double_axis3_angle3_between_directions) {
    extended_rotation::between_directions<double, 3, 3>();
}

CH_TEST(functional_rotation_double_axis3_angle3_interpolation_arc) {
    extended_rotation::interpolation_arc<double, 3, 3>();
}
