// Generated by scripts/generate_extended_tests.py; edit the scenario table there.
// clang-format off
#include "extended/performance_cases.hpp"

CH_TEST(perf_extended_float_batch_vectors) {
    extended_perf::run<float, 0>();
}

CH_TEST(perf_extended_float_batch_rotation) {
    extended_perf::run<float, 1>();
}

CH_TEST(perf_extended_float_batch_normalize) {
    extended_perf::run<float, 2>();
}

CH_TEST(perf_extended_float_batch_cross) {
    extended_perf::run<float, 3>();
}

CH_TEST(perf_extended_float_matrix_rhs) {
    extended_perf::run<float, 4>();
}

CH_TEST(perf_extended_float_bezier_joint) {
    extended_perf::run<float, 5>();
}

CH_TEST(perf_extended_float_cubic_horner) {
    extended_perf::run<float, 6>();
}

CH_TEST(perf_extended_float_prepared_ray) {
    extended_perf::run<float, 7>();
}

CH_TEST(perf_extended_float_frustum_batch) {
    extended_perf::run<float, 8>();
}

CH_TEST(perf_extended_float_rectangular_matrix) {
    extended_perf::run<float, 9>();
}

CH_TEST(perf_extended_double_batch_vectors) {
    extended_perf::run<double, 0>();
}

CH_TEST(perf_extended_double_batch_rotation) {
    extended_perf::run<double, 1>();
}

CH_TEST(perf_extended_double_batch_normalize) {
    extended_perf::run<double, 2>();
}

CH_TEST(perf_extended_double_batch_cross) {
    extended_perf::run<double, 3>();
}

CH_TEST(perf_extended_double_matrix_rhs) {
    extended_perf::run<double, 4>();
}

CH_TEST(perf_extended_double_bezier_joint) {
    extended_perf::run<double, 5>();
}

CH_TEST(perf_extended_double_cubic_horner) {
    extended_perf::run<double, 6>();
}

CH_TEST(perf_extended_double_prepared_ray) {
    extended_perf::run<double, 7>();
}

CH_TEST(perf_extended_double_frustum_batch) {
    extended_perf::run<double, 8>();
}

CH_TEST(perf_extended_double_rectangular_matrix) {
    extended_perf::run<double, 9>();
}
