// Generated by scripts/generate_extended_tests.py; edit the scenario table there.
// clang-format off
#include "extended/contract_cases.hpp"

CH_TEST(boundary_contract_float_rotation_invalid) {
    extended_contract::run<float, 0>();
}

CH_TEST(boundary_contract_float_normalize_mixed) {
    extended_contract::run<float, 1>();
}

CH_TEST(boundary_contract_float_cross_overlap) {
    extended_contract::run<float, 2>();
}

CH_TEST(boundary_contract_float_normalize_aos_overlap) {
    extended_contract::run<float, 3>();
}

CH_TEST(boundary_contract_float_multiple_rhs_nonfinite) {
    extended_contract::run<float, 4>();
}

CH_TEST(boundary_contract_float_multiple_rhs_subnormal) {
    extended_contract::run<float, 5>();
}

CH_TEST(boundary_contract_float_prepared_invalid) {
    extended_contract::run<float, 6>();
}

CH_TEST(boundary_contract_float_prepared_extremes) {
    extended_contract::run<float, 7>();
}

CH_TEST(boundary_contract_float_prepared_tangent) {
    extended_contract::run<float, 8>();
}

CH_TEST(boundary_contract_float_intersect_size) {
    extended_contract::run<float, 9>();
}

CH_TEST(boundary_contract_float_classify_size) {
    extended_contract::run<float, 10>();
}

CH_TEST(boundary_contract_float_cubic_invalid) {
    extended_contract::run<float, 11>();
}

CH_TEST(boundary_contract_float_cubic_derivatives) {
    extended_contract::run<float, 12>();
}

CH_TEST(boundary_contract_float_bezier_constant) {
    extended_contract::run<float, 13>();
}

CH_TEST(boundary_contract_double_rotation_invalid) {
    extended_contract::run<double, 0>();
}

CH_TEST(boundary_contract_double_normalize_mixed) {
    extended_contract::run<double, 1>();
}

CH_TEST(boundary_contract_double_cross_overlap) {
    extended_contract::run<double, 2>();
}

CH_TEST(boundary_contract_double_normalize_aos_overlap) {
    extended_contract::run<double, 3>();
}

CH_TEST(boundary_contract_double_multiple_rhs_nonfinite) {
    extended_contract::run<double, 4>();
}

CH_TEST(boundary_contract_double_multiple_rhs_subnormal) {
    extended_contract::run<double, 5>();
}

CH_TEST(boundary_contract_double_prepared_invalid) {
    extended_contract::run<double, 6>();
}

CH_TEST(boundary_contract_double_prepared_extremes) {
    extended_contract::run<double, 7>();
}

CH_TEST(boundary_contract_double_prepared_tangent) {
    extended_contract::run<double, 8>();
}

CH_TEST(boundary_contract_double_intersect_size) {
    extended_contract::run<double, 9>();
}

CH_TEST(boundary_contract_double_classify_size) {
    extended_contract::run<double, 10>();
}

CH_TEST(boundary_contract_double_cubic_invalid) {
    extended_contract::run<double, 11>();
}

CH_TEST(boundary_contract_double_cubic_derivatives) {
    extended_contract::run<double, 12>();
}

CH_TEST(boundary_contract_double_bezier_constant) {
    extended_contract::run<double, 13>();
}

CH_TEST(boundary_projection_float_convention0) {
    extended_contract::projection<float, 0>();
}

CH_TEST(boundary_projection_float_convention1) {
    extended_contract::projection<float, 1>();
}

CH_TEST(boundary_projection_float_convention2) {
    extended_contract::projection<float, 2>();
}

CH_TEST(boundary_projection_float_convention3) {
    extended_contract::projection<float, 3>();
}

CH_TEST(boundary_projection_float_convention4) {
    extended_contract::projection<float, 4>();
}

CH_TEST(boundary_projection_float_convention5) {
    extended_contract::projection<float, 5>();
}

CH_TEST(boundary_projection_float_convention6) {
    extended_contract::projection<float, 6>();
}

CH_TEST(boundary_projection_float_convention7) {
    extended_contract::projection<float, 7>();
}

CH_TEST(boundary_projection_double_convention0) {
    extended_contract::projection<double, 0>();
}

CH_TEST(boundary_projection_double_convention1) {
    extended_contract::projection<double, 1>();
}

CH_TEST(boundary_projection_double_convention2) {
    extended_contract::projection<double, 2>();
}

CH_TEST(boundary_projection_double_convention3) {
    extended_contract::projection<double, 3>();
}

CH_TEST(boundary_projection_double_convention4) {
    extended_contract::projection<double, 4>();
}

CH_TEST(boundary_projection_double_convention5) {
    extended_contract::projection<double, 5>();
}

CH_TEST(boundary_projection_double_convention6) {
    extended_contract::projection<double, 6>();
}

CH_TEST(boundary_projection_double_convention7) {
    extended_contract::projection<double, 7>();
}
