// Generated by scripts/generate_extended_tests.py; edit the scenario table there.
// clang-format off
#include "extended/curve_cases.hpp"

CH_TEST(functional_curve_float_degree1_polynomial_oracle) {
    extended_curve::polynomial_oracle<float, 1>();
}

CH_TEST(functional_curve_float_degree1_joint_derivative) {
    extended_curve::joint_derivative<float, 1>();
}

CH_TEST(functional_curve_float_degree1_split_reparameterization) {
    extended_curve::split_reparameterization<float, 1>();
}

CH_TEST(functional_curve_float_degree1_spline_bezier_equivalence) {
    extended_curve::spline_bezier_equivalence<float, 1>();
}

CH_TEST(functional_curve_float_degree1_rational_reference) {
    extended_curve::rational_reference<float, 1>();
}

CH_TEST(functional_curve_float_degree1_nonclamped_derivative) {
    extended_curve::nonclamped_derivative<float, 1>();
}

CH_TEST(functional_curve_float_degree2_polynomial_oracle) {
    extended_curve::polynomial_oracle<float, 2>();
}

CH_TEST(functional_curve_float_degree2_joint_derivative) {
    extended_curve::joint_derivative<float, 2>();
}

CH_TEST(functional_curve_float_degree2_split_reparameterization) {
    extended_curve::split_reparameterization<float, 2>();
}

CH_TEST(functional_curve_float_degree2_spline_bezier_equivalence) {
    extended_curve::spline_bezier_equivalence<float, 2>();
}

CH_TEST(functional_curve_float_degree2_rational_reference) {
    extended_curve::rational_reference<float, 2>();
}

CH_TEST(functional_curve_float_degree2_nonclamped_derivative) {
    extended_curve::nonclamped_derivative<float, 2>();
}

CH_TEST(functional_curve_float_degree3_polynomial_oracle) {
    extended_curve::polynomial_oracle<float, 3>();
}

CH_TEST(functional_curve_float_degree3_joint_derivative) {
    extended_curve::joint_derivative<float, 3>();
}

CH_TEST(functional_curve_float_degree3_split_reparameterization) {
    extended_curve::split_reparameterization<float, 3>();
}

CH_TEST(functional_curve_float_degree3_spline_bezier_equivalence) {
    extended_curve::spline_bezier_equivalence<float, 3>();
}

CH_TEST(functional_curve_float_degree3_rational_reference) {
    extended_curve::rational_reference<float, 3>();
}

CH_TEST(functional_curve_float_degree3_nonclamped_derivative) {
    extended_curve::nonclamped_derivative<float, 3>();
}

CH_TEST(functional_curve_float_degree8_polynomial_oracle) {
    extended_curve::polynomial_oracle<float, 8>();
}

CH_TEST(functional_curve_float_degree8_joint_derivative) {
    extended_curve::joint_derivative<float, 8>();
}

CH_TEST(functional_curve_float_degree8_split_reparameterization) {
    extended_curve::split_reparameterization<float, 8>();
}

CH_TEST(functional_curve_float_degree8_spline_bezier_equivalence) {
    extended_curve::spline_bezier_equivalence<float, 8>();
}

CH_TEST(functional_curve_float_degree8_rational_reference) {
    extended_curve::rational_reference<float, 8>();
}

CH_TEST(functional_curve_float_degree8_nonclamped_derivative) {
    extended_curve::nonclamped_derivative<float, 8>();
}

CH_TEST(functional_curve_double_degree1_polynomial_oracle) {
    extended_curve::polynomial_oracle<double, 1>();
}

CH_TEST(functional_curve_double_degree1_joint_derivative) {
    extended_curve::joint_derivative<double, 1>();
}

CH_TEST(functional_curve_double_degree1_split_reparameterization) {
    extended_curve::split_reparameterization<double, 1>();
}

CH_TEST(functional_curve_double_degree1_spline_bezier_equivalence) {
    extended_curve::spline_bezier_equivalence<double, 1>();
}

CH_TEST(functional_curve_double_degree1_rational_reference) {
    extended_curve::rational_reference<double, 1>();
}

CH_TEST(functional_curve_double_degree1_nonclamped_derivative) {
    extended_curve::nonclamped_derivative<double, 1>();
}

CH_TEST(functional_curve_double_degree2_polynomial_oracle) {
    extended_curve::polynomial_oracle<double, 2>();
}

CH_TEST(functional_curve_double_degree2_joint_derivative) {
    extended_curve::joint_derivative<double, 2>();
}

CH_TEST(functional_curve_double_degree2_split_reparameterization) {
    extended_curve::split_reparameterization<double, 2>();
}

CH_TEST(functional_curve_double_degree2_spline_bezier_equivalence) {
    extended_curve::spline_bezier_equivalence<double, 2>();
}

CH_TEST(functional_curve_double_degree2_rational_reference) {
    extended_curve::rational_reference<double, 2>();
}

CH_TEST(functional_curve_double_degree2_nonclamped_derivative) {
    extended_curve::nonclamped_derivative<double, 2>();
}

CH_TEST(functional_curve_double_degree3_polynomial_oracle) {
    extended_curve::polynomial_oracle<double, 3>();
}

CH_TEST(functional_curve_double_degree3_joint_derivative) {
    extended_curve::joint_derivative<double, 3>();
}

CH_TEST(functional_curve_double_degree3_split_reparameterization) {
    extended_curve::split_reparameterization<double, 3>();
}

CH_TEST(functional_curve_double_degree3_spline_bezier_equivalence) {
    extended_curve::spline_bezier_equivalence<double, 3>();
}

CH_TEST(functional_curve_double_degree3_rational_reference) {
    extended_curve::rational_reference<double, 3>();
}

CH_TEST(functional_curve_double_degree3_nonclamped_derivative) {
    extended_curve::nonclamped_derivative<double, 3>();
}

CH_TEST(functional_curve_double_degree8_polynomial_oracle) {
    extended_curve::polynomial_oracle<double, 8>();
}

CH_TEST(functional_curve_double_degree8_joint_derivative) {
    extended_curve::joint_derivative<double, 8>();
}

CH_TEST(functional_curve_double_degree8_split_reparameterization) {
    extended_curve::split_reparameterization<double, 8>();
}

CH_TEST(functional_curve_double_degree8_spline_bezier_equivalence) {
    extended_curve::spline_bezier_equivalence<double, 8>();
}

CH_TEST(functional_curve_double_degree8_rational_reference) {
    extended_curve::rational_reference<double, 8>();
}

CH_TEST(functional_curve_double_degree8_nonclamped_derivative) {
    extended_curve::nonclamped_derivative<double, 8>();
}
