#!/usr/bin/env python3
"""Materialize reviewed type/dimension/scenario combinations as named CTest cases.

Each name encodes its distinct inputs and contract. Shared helper bodies avoid
copying assertion logic; changing only a random seed does not create a case.
Generated C++ is checked in and needs no generator or Python during builds.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def suite(name, header, cases, check=False):
    lines = [f'// Generated by scripts/generate_extended_tests.py; edit the scenario table there.',
             '// clang-format off', f'#include "extended/{header}"', '']
    for label, call in cases:
        lines += [f'CH_TEST({label}) {{', f'    {call};', '}', '']
    text = '\n'.join(lines)
    path = ROOT / 'tests' / f'test_extended_{name}.cpp'
    if check:
        if not path.exists() or path.read_text(encoding='utf-8') != text:
            raise SystemExit(f'Generated cases need updating: {path}')
    else:
        path.write_text(text, encoding='utf-8', newline='\n')
    print(f'{name}: {len(cases)} named cases')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    vector_ops = ('addition','subtraction','scaling','component_product','dot_reference',
                  'normalize_reference','projection_residual','angle_invariants','length_extremes','packed_storage')
    matrix_ops = ('product_oracle','transpose_contract','arithmetic','triangular_determinant',
                  'solve_known_solution','multiple_rhs','two_sided_inverse','small_scale_lu',
                  'qr_reconstruction','cholesky_reconstruction','eigen_residuals','self_assignment')
    suite('vector','vector_cases.hpp',[(f'functional_vector_{t}_n{n}_{op}',f'extended_vector::{op}<{t}, {n}>()')
          for t in ('float','double') for n in (1,2,3,4,8,16) for op in vector_ops],args.check)
    suite('matrix','matrix_cases.hpp',[(f'functional_matrix_{t}_n{n}_{op}',f'extended_matrix::{op}<{t}, {n}>()')
          for t in ('float','double') for n in (1,2,3,4,8) for op in matrix_ops],args.check)
    suite('rotation','rotation_cases.hpp',[(f'functional_rotation_{t}_axis{axis}_angle{angle}_{op}',f'extended_rotation::{op}<{t}, {axis}, {angle}>()')
          for t in ('float','double') for axis in range(4) for angle in range(4)
          for op in ('rodrigues_reference','between_directions','interpolation_arc')],args.check)
    suite('curve','curve_cases.hpp',[(f'functional_curve_{t}_degree{degree}_{op}',f'extended_curve::{op}<{t}, {degree}>()')
          for t in ('float','double') for degree in (1,2,3,8)
          for op in ('polynomial_oracle','joint_derivative','split_reparameterization','spline_bezier_equivalence','rational_reference','nonclamped_derivative')],args.check)
    suite('numeric','numeric_cases.hpp',[(f'functional_numeric_{t}_{op}_scenario{case}',f'extended_numeric::{op}<{t}, {case}>()')
          for t in ('float','double') for op in ('quadratic_roots_known','horner_reference','bisect_irrational','integrate_polynomial','compensated_cancellation','bounded_root_work')
          for case in range(4)],args.check)
    suite('batch','batch_cases.hpp',[(f'safety_batch_{t}_{op}_size{n}',f'extended_batch::guarded_contract<{t}, {index}, {n}>()')
          for t in ('float','double') for index,op in enumerate(('points','vectors','rotation','dot','cross','normalize'))
          for n in (0,1,2,3,4,5,7,8,9,15,16,17)],args.check)
    contract_ops=('rotation_invalid','normalize_mixed','cross_overlap','normalize_aos_overlap',
                  'multiple_rhs_nonfinite','multiple_rhs_subnormal','prepared_invalid','prepared_extremes',
                  'prepared_tangent','intersect_size','classify_size','cubic_invalid','cubic_derivatives','bezier_constant')
    suite('contract','contract_cases.hpp',[(f'boundary_contract_{t}_{op}',f'extended_contract::run<{t}, {index}>()')
          for t in ('float','double') for index,op in enumerate(contract_ops)] +
          [(f'boundary_projection_{t}_convention{mode}',f'extended_contract::projection<{t}, {mode}>()')
           for t in ('float','double') for mode in range(8)],args.check)
    suite('stress','stress_cases.hpp',[(f'stress_{t}_{op}_tier{tier}',f'extended_stress::run<{t}, {index}, {tier}>()')
          for t in ('float','double') for index,op in enumerate(('normalization','rotation_chain','affine_chain','lu_reuse','ray_grid',
              'spline_sampling','batch_pipeline','conditioned_inverse','integration','concurrent_readers')) for tier in range(3)],args.check)
    suite('performance','performance_cases.hpp',[(f'perf_extended_{t}_{op}',f'extended_perf::run<{t}, {index}>()')
          for t in ('float','double') for index,op in enumerate(('batch_vectors','batch_rotation','batch_normalize','batch_cross','matrix_rhs',
              'bezier_joint','cubic_horner','prepared_ray','frustum_batch','rectangular_matrix'))],args.check)


if __name__ == '__main__':
    main()
